apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-app
spec:
  selector:
    matchLabels:
      app: demo-go-test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-go-test-app
    spec:
      containers:
      - name: go-app-container
        image: alex43/go-demo-app:v1.0
        ports:
        - containerPort: 8080
